server:
  port: 8085
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Dictionary?useUnicode=yes&characterEncoding=UTF-8
    username: postgres
    password: vampyrrr9712
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    logging:
      level:
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE